language: node_js

node_js:
  - "12.16.1"

dist: trusty

# services: mongodb
env: NODE_ENF=production

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run test
  - npm install --prefix client
  - npm run test --prefix client
  - npm run build --prefix client
